### ISSUE TITLE
stage01-1でうろうろしてるだけでゲームオーバーになる

### ISSUE THREAD

**Issue by usk83** [usk83/JavaMario#30]
このステージはクリボーが複数いるので、クリボーとのあたり判定の部分がおかしい可能性が高い。

**Comment by yas-nyan** [comment]
うーん　マジすか

**Comment by yas-nyan** [comment]
確かに1-1では再現しましたが、クリボーが複数いるステージでもスクロールの無いステージは再現しませんでした

**Comment by usk83** [comment]
おお、確認してる感じいいね

俺も同じことを確認してた。すると01-1は横幅がめっちゃ広いから、それがどっかで悪さしてるのかな

**Comment by usk83** [comment]
まあ、特定の条件下でしか発生しないから、直さなくていいけどね！

**Comment by usk83** [comment]
原因わかった
マリオに限らず、クリボーとかが穴に落ちてもゲームオーバーになる

**Comment by yas-nyan** [comment]
修正完了
マージ待https://github.com/usk83/JavaMario/pull/33
